### ISSUE TITLE
Hey RexyRexy

### ISSUE THREAD

**Issue by Xelamats** [rexyrexy/PortedAddons#1]
Fking scum

**Comment by lgndz** [comment]
#savage

**Comment by rexyrexy** [comment]
Im soooo savage. Yeah i have much money.For saling portaio jasıdajsd Now i can travel to world hahahaah

**Comment by Xelamats** [comment]
Oh, nice. "Now i can travel to world"; Which world are you going to travel to?

**Comment by lushisop** [comment]
LOL

**Comment by lgndz** [comment]
Lmaooo

Sent from Outlook Mobile, please excuse any errors or shorthand.




On Mon, May 16, 2016 at 7:14 PM -0700, "Lush" <notifications@github.com> wrote:












LOL

**Comment by rexyrexy** [comment]
Leave this area or don't speak like a idiot. I'M NOT SALE OR SOLD PORTAIO!!

I mean world tour with my money for saying Travel to world sorry about my english..
