### ISSUE TITLE
Hey,REXY

### ISSUE THREAD

**Issue by hardique** [rexyrexy/PortedAddons#2]
U r a fcking retard,who stole berbb`s work and portaio and now trying to sell.

DONT PAY HIM.IT IS FREE

**Comment by rexyrexy** [comment]
Where you hearing it ? Ohh i have billions dollars on my paypal for sale nothing hahaah

**Comment by rexyrexy** [comment]
Leave this area or don't speak like a idiot. I'M NOT SALE OR SOLD PORTAIO!!
