### ISSUE TITLE
WIHAY YOU SELLİNG PORt AYIOO

### ISSUE THREAD

**Issue by Sezaiisback** [rexyrexy/PortedAddons#4]
THIS MANİİ HARAM ZIKKIM OLMAK YOUU YUUHHH YUHHH BİJİ SEROK BERB :)))))))))))

**Comment by rexyrexy** [comment]
ahahaha i like it 

childs are soooo good.. :+1:

**Comment by Xelamats** [comment]
"childs are soooo good.."; You fucking pedophile. That's disgusting. You should be ashamed of yourself.

**Comment by lushisop** [comment]
LOL

**Comment by rexyrexy** [comment]
Retard kids or childs are sooo good really..

**Comment by rexyrexy** [comment]
Leave this area or don't speak like a idiot. I'M NOT SALE OR SOLD PORTAIO!!
